# NUMPY

NumPy is a Python library that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. 

NumPy introduces a powerful data structure called the "array," which is similar to a list but allows you to perform operations on entire sets of data at once. Arrays are efficient and fast for numerical operations. They enable you to work with large datasets more easily than standard Python lists. NumPy can automatically apply operations to arrays of different shapes and sizes, making your code more flexible. 

In essence, NumPy simplifies numerical computing in Python by providing efficient ways to work with large datasets and perform mathematical operations. It's a foundational library for various scientific and data-related tasks, making it an essential tool for anyone working with numerical data in Python.

### Import NumPy

In [76]:
import numpy as np

This line imports the NumPy library and gives it the alias np. The np alias is a common convention used by the Python community when working with NumPy. After this import statement, you can use NumPy functions and classes by prefixing them with np..

### Checking NumPy Version

In [77]:
print(np.__version__)

1.24.3


It means that you have NumPy version 1.24.3 installed. Checking the version is useful because different versions of a library may have different features, bug fixes, or improvements. It helps you ensure that your code is compatible with the version of NumPy you're using and allows you to check for updates or verify compatibility with other libraries.

### Creating a NumPy Array

In [78]:
arr = np.array([2,4,6,8,10])
print(arr)

[ 2  4  6  8 10]


This indicates that arr is a one-dimensional array containing the values 2, 4, 6, 8, and 10. The square brackets [...] denote an array in the output, and the numbers are the elements of the array.The code creates a NumPy array with five elements and prints its contents. 

### Check Type array

In [79]:
arr = np.array([2,4,6,8,10])

print(arr)

print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


This code demonstrates the creation of a simple one-dimensional NumPy array and confirms its data type, showcasing the use of NumPy in handling numerical data efficiently.

## Use a Tupple to Create a NumPy Array

In [80]:
arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


The provided code creates a NumPy array named arr using the np.array() function with a tuple containing the elements 1, 2, 3, 4, and 5. The print(arr) statement displays the contents of the array, resulting in the output [1 2 3 4 5].

## Dimmension in Arrays

In NumPy, the term "dimension" refers to the number of axes or directions in which data can vary. Arrays in NumPy can have one or more dimensions, and the number of dimensions is often referred to as the "rank" of the array.

### Create a 0-D array

A 0D array is a scalar, representing a single, unique value. It has zero dimensions because there is no need for an index to access its value.

Example:

In [81]:
import numpy as np

arr = np.array(12.2)

print(arr)

12.2


### Create a 1-D array

A 1D array is a collection of values along a single axis. It has one dimension because you need one index to access each element along the single axis.

Example:

In [82]:
arr = np.array(['a','b','c'])

print(arr)

['a' 'b' 'c']


### Create a 2-D array

A 2D array is a table of values organized in rows and columns.It has two dimensions – rows and columns. You need two indices (row and column) to access an element.

Example:

In [83]:
arr = np.array([['d','a'], ['t','a']])

print(arr)

[['d' 'a']
 ['t' 'a']]


### Create a 3-D array with two 

A 3-D array with two 2x3 matrices, where the outermost layer represents the first dimension, and each inner layer represents a 2-D matrix.

In [84]:
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check how many dimensions the arrays have

In [85]:
a = np.array(4.2)
b = np.array(['a','b','c'])
c = np.array([['d','a'], ['t','a']])
d = np.array([[['data'], ['analyst']], [['kelompok'], ['tiga']]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


The ndim attribute is crucial for understanding the structure and dimensionality of NumPy arrays. It helps you determine how many indices or axes are needed to access elements in the array.

### Create an array with 7 dimensions and verify that it has 7 dimensions

In [86]:
import numpy as np

arr = np.array(['data analyst kelas D'], ndmin=7)

print(arr)

[[[[[[['data analyst kelas D']]]]]]]


In NumPy, the ndmin parameter is used when creating an array to specify the minimum number of dimensions that the resulting array should have. It allows you to explicitly set the number of dimensions, ensuring that the array has at least the specified minimum dimensions.

### get the first element from the following array

In [87]:
import numpy as np

arr = np.array(['a','b','c'])

print(arr[0])

a


### get the second element from the following array

In [88]:
import numpy as np

arr = np.array(['a','b','c'])

print(arr[1])

b


### get third and fourth elements and add them

In [89]:
arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7


### access the element on the first row, second column

In [90]:
arr = np.array([[1,2,3], [4,5,6]])

print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


### access the element on the 2nd row, 5th column

In [91]:
arr = np.array([[1,2,3], [4,5,6]])

print('5th element on 2nd row: ', arr[0,1])

5th element on 2nd row:  2


## TASK 

In [92]:
arr = np.array([[2,3,4,5,6], [4,5,6,7,8]])

print(arr)
print(arr[1,3])
print(arr[0,2])
print(arr[1,3]+arr[0,2])
print(arr[1,1:2])

[[2 3 4 5 6]
 [4 5 6 7 8]]
7
[0, 2]
11
[5]


### access the 3rd element of the second array of the first array

In [93]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

print(arr[1,0,2])

9


### print the last element from the 2nd dim

In [94]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('last element from 2nd dim: ',arr[1,-1])

last element from 2nd dim:  10
